Move column specific formatting into a new dropdown section
deephaven/web-client-ui pull request #1002
Opened 2023-01-10 14:17 UTC by emilyhuxng

[#994](https://github.com/deephaven/web-client-ui/issues/994)

I removed the code returning column specific formatting and any code that becomes unnecessary afterwards in FormattingSectionContent. Then in ColumnSpecificSectionContent, I took the original code and did the same thing but removed code related to Timezone formatting.

Also renamed the sections.

2023-01-10 14:31 UTC, emilyhuxng commented
I have read the CLA Document and I hereby sign the CLA

2023-01-10 14:39 UTC, mofojed requested changes
Looks great!
Minor change - in the PR description, change it to say "Fixes #994" instead of just "#994". By adding the "Fixes" keyword, it will close the ticket #994 when this is merged.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2023-01-10 14:57 UTC, mofojed requested changes

2023-01-10 14:57 UTC, mofojed commented on packages/code-studio/src/settings/ColumnSpecificSectionContent.tsx
> +  }
I think all of these static methods are also used in `FormattingSectionContent`. You should refactor these into their own utils file, e.g. `SettingsUtils.ts`. See `FormatterUtils.ts` for an example of a utils file (exporting a bunch of functions).

2023-01-10 18:51 UTC, mofojed approved these changes
A couple minor style suggestions, looks great!

2023-01-10 18:51 UTC, mofojed commented on packages/code-studio/src/settings/ColumnSpecificSectionContent.tsx
> +import SettingsUtils from './SettingsUtils';
You could also import just the functions you use directly, so you don't need to call `SettingsUtils.*` each time, e.g. 

```
import { focusFirstInputInContainer } from './SettingsUtils';
...
  componentDidMount(): void {
    focusFirstInputInContainer(this.containerRef.current);
  }
```

2023-01-10 18:51 UTC, mofojed commented on packages/code-studio/src/settings/SettingsUtils.tsx
> +}
These static functions are essentially just functional React components, they could be put into their own files, e.g. `TimeZoneOptions.tsx`, `ColumnTypeOptions.tsx`, and `DateTimeOptions.tsx`. Not a big deal though.

2023-01-11 14:49 UTC, mofojed requested changes

2023-01-11 14:49 UTC, mofojed commented on packages/code-studio/src/settings/ColumnTypeOptions.tsx
> +  ];
This const could be initialized outside of the function.

2023-01-11 14:49 UTC, mofojed commented on packages/code-studio/src/settings/DateTimeOptions.tsx
> +): ReactElement[] {
Should make this a functional component, e.g.

```
interface DateTimeOptionsProps {
  timestamp: Date;
  timeZone: string;
  showTimeZone: boolean;
  showTSeparator: boolean;
  isGlobalOptions: boolean;
  legacyGlobalFormat?: string;
}

export default function DateTimeOptions(props: DateTimeOptionsProps) {
  ...
}
```

2023-01-11 14:49 UTC, mofojed commented on packages/code-studio/src/settings/TimeZoneOptions.tsx
> +export default function renderTimeZoneOptions(): JSX.Element[] {
Make this a function component, e.g.
```
export default function TimeZoneOptions(): JSX.Element {
  ...
}
```

2023-01-12 14:35 UTC, mofojed approved these changes
Looking good. How are the tests coming?

2023-01-12 14:37 UTC, emilyhuxng commented
> Looking good. How are the tests coming?

I have 100% code coverage but branch coverage is at 85% so I am working on that.

2023-01-12 15:14 UTC, merged