Fix cell overflow viewer with browser zoom
deephaven/web-client-ui pull request #1029
Opened 2023-01-17 19:16 UTC by emilyhuxng

Fixes #834 

Set the height when the editor is initialized.

2023-01-18 00:29 UTC, mattrunyon commented
Looks good. Can you add a `size='xl'` to the overflow modal? Looks like it was removed by mistake in #611. This should give us more width when needed up to a certain amount. It does introduce a little weirdness when zooming in since you can cross the browser size thresholds in bootstrap and actually get a smaller (by percent) modal, but I wouldn't worry about that for now

2023-01-18 00:29 UTC, mattrunyon requested changes
Looks good. Can you add a `size='xl'` to the overflow modal? Looks like it was removed by mistake in #611. This should give us more width when needed up to a certain amount. It does introduce a little weirdness when zooming in since you can cross the browser size thresholds in bootstrap and actually get a smaller (by percent) modal, but I wouldn't worry about that for now

2023-01-18 17:03 UTC, mattrunyon approved these changes

2023-01-19 20:20 UTC, mofojed approved these changes

2023-01-19 20:24 UTC, merged