File Explorer drag and drop to move files
deephaven/web-client-ui pull request #109
Opened 2021-07-13 15:38 UTC by mofojed

- Add back the drag and drop to move files functionality
- Switch FileList to use ItemList instead of SingleClickItemList; this allowed removing the FileListItem type entirely and just using FileStorageItem
- Changed `keyboardIndex` to `focusIndex` in `ItemList`, and fire an `onFocusChange` event to allow handling.
- Update selection after drop
- Expand a folder by hovering over it while dragging files
- Emit signal for all renamed files
- Converted ItemList unit tests to tsx, added some more
- Don't focus a notebook panel when opening it in preview mode (cursor was getting lost in file list)
- Fixed up MockIrisGridModel so styleguide works correctly
Fixes #86

2021-07-21 17:39 UTC, mofojed commented
Adding @dsmmcken to review styling

2021-07-22 18:16 UTC, vbabich requested changes

2021-07-22 18:16 UTC, vbabich commented on packages/file-explorer/src/FileList.tsx
> +    : FileUtils.getPath(targetItem.filename);
```suggestion
  const targetPath = getPathFromItem(targetItem);
```

2021-07-22 18:44 UTC, mofojed commented on packages/file-explorer/src/FileList.tsx
> +          // TODO: still needed??
Yup I didn't need this with the new AutoSizer, I'll take out this updateDimensions wiring

2021-07-22 20:22 UTC, dsmmcken submitted a review, later dismissed
- [x] 1. Dragging folder into self deletes folder 😨 
- [x] 2, Styling of selection should match command history exactly see commandhistoryitem.scss, maybe even re-use? note the use of focus, active, hover, focus-within active styling and borders.
- [x] 3. Selecting multiple items, then initiating a drag shows the drag item that initiated as de-selected, rather than remaining selected
- [x] 4.  ctrl/shift selection clicks shouldn't trigger opening of that notebook.

2021-07-22 20:59 UTC, vbabich commented
- [ ] In Chrome/Mac the cursor has a green "+" icon when dragging items

2021-07-23 13:58 UTC, mofojed commented
@dsmmcken Should I be building the border/transitions directly into ItemList? Not sure if there was a reason that styling was only added to command history or not.

In any case I've pushed a change with the styling applied to FileList

2021-07-23 15:21 UTC, dsmmcken commented
> @dsmmcken Should I be building the border/transitions directly into ItemList? Not sure if there was a reason that styling was only added to command history or not.
> 
> In any case I've pushed a change with the styling applied to FileList

Could re-use between filelist and command history list, but this list is also used a bunch in the table sidebar menu, where it has different styling

2021-07-23 21:44 UTC, vbabich submitted a review, later dismissed

2021-07-23 22:05 UTC, vbabich approved these changes

2021-07-23 22:14 UTC, merged