fix: Conditional date formatting
deephaven/web-client-ui pull request #1104
Opened 2023-02-23 23:18 UTC by bmingles

Conditional formatting for date columns now properly prevents conditions with empty values from being applied.

2023-02-23 23:32 UTC, bmingles commented
I have read the CLA Document and I hereby sign the CLA

2023-02-24 19:08 UTC, vbabich requested changes

2023-02-24 19:08 UTC, vbabich commented on packages/iris-grid/src/sidebar/conditional-formatting/ConditionalFormattingUtils.ts
> +      // TODO: we need to validate whether a given string can be parsed as a date
We usually avoid merging TODOs. Either fix the issue or file a ticket for it.

2023-02-27 18:43 UTC, vbabich approved these changes

2023-02-27 18:56 UTC, merged