feat: Add clickable links in cell overflow modal
deephaven/web-client-ui pull request #1147
Opened 2023-03-13 19:12 UTC by emilyhuxng

Closes #1128 

Links without `https` are also recognized as links. I couldn't figure out how to disable the tooltip or open the link upon left click.

2023-03-14 17:50 UTC, emilyhuxng commented
> I noticed some inconsistency between clicking e-mail addresses vs. URIs - e-mails try to open in the same window, whereas URIs open in a separate window.

This might be a browser setting? For me, it's doing the same thing as the cells. Urls open in a new tab if you click follow link, redirecting you to the tab. If you control click, it opens in a new tab in the background in the same window. Emails open the mail app.

> I noticed that with links: true (which should be the [default according to docs](https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorOptions.html#links)? Not sure why it's not defaulting to clickable) it handles hyperlinking URIs correctly, but doesn't seem to pick up e-mails. Were there any other cases you noticed?

Other than emails, it doesn't detect links without `https` like `google.com`. That is fine, but it would be inconsistent with the cells.

2023-03-14 17:52 UTC, emilyhuxng commented on packages/console/src/notebook/Editor.tsx
> +        const text = model.getValue();
What about links that span over one line?

2023-03-14 17:58 UTC, dsmmcken commented
Ctrl+click is a non-continuous selection behavior in grid, and we wouldn't want to change that.

2023-03-14 20:08 UTC, mofojed commented
> > I noticed some inconsistency between clicking e-mail addresses vs. URIs - e-mails try to open in the same window, whereas URIs open in a separate window.
> 
> This might be a browser setting? For me, it's doing the same thing as the cells. Urls open in a new tab if you click follow link, redirecting you to the tab. If you control click, it opens in a new tab in the background in the same window. Emails open the mail app.
Yes, this is true. In Chrome settings in chrome://settings/handlers?search=protocol+handler, I have GMail set up to be the default email handler:
![image](https://user-images.githubusercontent.com/4505624/225124050-9e2d1cde-cd28-40ba-b4c2-9ccebc7cd212.png)
Full instructions here: https://www.indeed.com/career-advice/career-development/how-to-get-email-links-to-open-in-chrome
Though now that it's set up, I don't know how to modify that setting... annoying that it tries to open in the same window, but okay.

2023-03-14 20:09 UTC, mofojed commented on packages/console/src/notebook/Editor.tsx
> +        const text = model.getValue();
In this case we're only looking for links, which can't span more than one line.

2023-03-17 13:34 UTC, mofojed requested changes

2023-03-17 13:34 UTC, mofojed commented on packages/console/src/monaco/MonacoUtils.ts
> +  static getProvideLinks = () => (model: monaco.editor.ITextModel) => {
No need to curry the method, just have it as a regular method:
```suggestion
  static provideLinks(model: monaco.editor.ITextModel) {
```

2023-03-17 13:34 UTC, mofojed commented on packages/console/src/notebook/Editor.tsx
> +      provideLinks: MonacoUtils.getProvideLinks(),
Without the method curried, can just do:
```suggestion
      provideLinks: MonacoUtils.provideLinks,
```

2023-03-20 13:01 UTC, mofojed requested changes

2023-03-20 14:24 UTC, dsmmcken requested changes
Can you check styling to format the links to have $primary color. Not sure if it might be part of the monaco theme variables

2023-03-20 16:04 UTC, dsmmcken submitted a review, later dismissed

2023-03-22 16:10 UTC, mofojed requested changes

2023-03-22 17:18 UTC, emilyhuxng commented on packages/console/src/notebook/Editor.scss
> +.monaco-editor .detected-link {
I think `textLink.foreground` controls the color of `Follow Link`, `textLink.activeForeground` controls when you hover over `Follow Link` and `editorLink.activeForeground` is when you hold your control key down over a link. I couldn't find anything for the actual visible links.

2023-03-22 18:20 UTC, mofojed commented on packages/console/src/notebook/Editor.scss
> +.monaco-editor .detected-link {
@dsmmcken what styling should we use? For regular links we add in [bootstrap_overrides.scss](https://github.com/deephaven/web-client-ui/blob/e314be6d32792aea3791ee5189fd45d37c86011c/packages/components/scss/bootstrap_overrides.scss#L196):
```
//links
$link-color: $gray-400;
$link-hover-color: $foreground;
```
But then for grid we use `$primary` and then don't add a hover colour.

Should we do the same for Monaco? (`textLink.foreground` and `.detected-link` as `$link-color`, then `textLnk.activeForeground` and `editorLink.activeForeground` as `$link-hover-color`)? Or use `$primary`

2023-03-22 19:13 UTC, dsmmcken commented on packages/console/src/notebook/Editor.scss
> +.monaco-editor .detected-link {
should probably all use link-color and link-hover-color when hovered. I don't think we can set the hover start in monaco as it looks like the link is split into multiple dom elements but I could be wrong.

We should also probably change link color to primary and primary-hover.

2023-03-27 16:44 UTC, mofojed approved these changes

2023-03-27 17:13 UTC, merged