feat: Update @vscode/codicons to v0.0.33
deephaven/web-client-ui pull request #1259
Opened 2023-05-02 19:50 UTC by dsmmcken

They renamed circle-large-outline to circle-large for consistency. Update adds several new icons.

I've fixed our usage to match for the renamed icon.

2023-05-02 22:48 UTC, mofojed requested changes
We should still add Breaking Change to this PR, as we're no longer exporting `vsCircleLargeOutline` from `@deephaven/icons`

2023-05-03 18:55 UTC, mofojed commented
Another option would be to re-export it with the old name to reduce breakage? But may be more hassle than it's worth.

2023-05-03 21:32 UTC, dsmmcken commented
better to let it break and update the other side I think, the name change makes sense.

2023-05-04 13:11 UTC, mofojed approved these changes

2023-05-04 14:59 UTC, merged