E2e fix
deephaven/web-client-ui pull request #1449
Opened 2023-08-15 18:31 UTC by ethanalvizo

2023-08-16 21:49 UTC, mattrunyon requested changes

2023-08-16 21:49 UTC, mattrunyon commented on tests/table-operations.spec.ts
> +    await page.getByTestId('btn-page-close').first().click();
This branch needs to be rebased or merge in main. These changes shouldn't be in this PR

2023-08-17 14:40 UTC, mattrunyon submitted a review, later dismissed

2023-08-17 18:25 UTC, mofojed approved these changes

2023-08-17 18:26 UTC, merged