fix: Remove totals table rows from displayed row count
deephaven/web-client-ui pull request #1492
Opened 2023-09-06 22:06 UTC by GcWan

Fixes #1407. When aggregations were added, both the table and column tooltips displayed an increased row count to account for the totals table. Rows from the totals table are now subtracted from the row count displayed to users.

2023-09-06 22:08 UTC, GcWan commented
I have read the CLA Document and I hereby sign the CLA

2023-09-07 14:52 UTC, mofojed requested changes
Need to handle case where aggregations are on top as well.

2023-09-07 14:52 UTC, mofojed commented on packages/dashboard-core-plugins/src/panels/IrisGridPanelTooltip.tsx
> +    (model?.floatingBottomRowCount ?? 0);
You'll also need to subtract `floatingTopRowCount`. Right now the total row count is incorrect if you move aggregations to the top:
![image](https://github.com/deephaven/web-client-ui/assets/4505624/fdb9bdaf-3606-4121-9613-9165e4f4973d)

2023-09-07 19:28 UTC, mofojed approved these changes

2023-09-07 19:29 UTC, mofojed commented
Great work!

2023-09-07 19:31 UTC, merged