Improve context menu selection in Command History/Item List
deephaven/web-client-ui pull request #155
Opened 2021-08-13 14:36 UTC by mofojed

- Right-click now updates the selection before showing context menu
- Fixes #154

2021-08-17 20:03 UTC, dsmmcken requested changes
Logic should be if the context click occurs on a selected row that is part of an existing selection , it should be maintained. (To match standard OS behaviour)

Only create a new selection if context menu click occurs on a blank row.

ie.

Select items a, b, c,
Context click on b, and copy
selection maintained, copied contents should be abc, not just b.

Context click on unselected item z, and copy
select z, and copied contents should be z

2021-08-17 20:14 UTC, mofojed commented
@dsmmcken If I'm being very accurate, should I also style context-selected items differently? On Mac OS it looks like they get an outline when context selected, as opposed to the primary selection format, eg:

Clicking outside existing selection:
![image](https://user-images.githubusercontent.com/4505624/129794024-6368722f-6ec6-4fca-a6da-1432994358e1.png)

Clicking inside existing selection:
![image](https://user-images.githubusercontent.com/4505624/129794124-b0141acf-fff1-4478-8484-233a9f098c00.png)

2021-08-17 20:33 UTC, dsmmcken commented
Counterpoint, win10 changes the selection, with no additional styling. So I would say we are safe to skip the extra styling work.

![right click](https://user-images.githubusercontent.com/1576283/129795915-6c002481-6cc0-46c9-aebd-ed423b82687c.gif)

2021-08-18 14:41 UTC, dsmmcken commented on packages/golden-layout/package-lock.json
> +  "version": "0.2.1",
should this be here?

2021-08-18 14:53 UTC, dsmmcken approved these changes
Approved for behaviour.

2021-08-19 19:35 UTC, vbabich approved these changes

2021-08-19 21:00 UTC, merged