fix: Date argument non-optional for the onChange prop
deephaven/web-client-ui pull request #1622
Opened 2023-11-03 16:38 UTC by sakibian

Closes: #1601

2023-11-03 16:43 UTC, sakibian commented
I have read the CLA Document and I hereby sign the CLA

2023-11-03 18:31 UTC, mofojed requested changes
Just remove the unnecessary comments. Thank you for the contribution!

2023-11-03 18:31 UTC, mofojed commented on packages/components/src/DateInput.tsx
> +  onChange: (date: string) => void; // Remove the question mark to make date non-optional
No need to add this comment here. 
```suggestion
  onChange: (date: string) => void;
```

2023-11-03 18:31 UTC, mofojed commented on packages/components/src/DateInput.tsx
> +      onChange = () => undefined, // Provide a default value for onChange
```suggestion
      onChange = () => undefined,
```

2023-11-03 18:31 UTC, mofojed commented on packages/components/src/DateInput.tsx
> -DateInput.defaultProps = {
Good cleanup!

2023-11-03 19:44 UTC, mofojed submitted a review, later dismissed
Thank you for the contribution!

2023-11-06 15:29 UTC, mofojed requested changes

2023-11-06 15:29 UTC, mofojed commented on packages/code-studio/src/styleguide/Inputs.tsx
> +  const handleChange = (date: string) => {
We've still got linter issues here - our formatting is fairly strict, we include some extensions and VS Code settings for automatically formatting code on save: https://github.com/deephaven/web-client-ui/blob/main/.vscode/settings.json

For this case though, I'm going to recommend the following:
- Make the `onChange` prop on `DateInput` optional still (the ticket was specifically for the `date` parameter on the callback to be marked as required, we don't need to make `onChange` itself required as well)
- Don't add an `onChange` here in the styleguide.

That would make it consistent with our existing behaviour/other components (such as `DateTimeInput`).

2023-11-10 15:06 UTC, mofojed approved these changes

2023-11-10 15:19 UTC, merged