feat: Add ResizeObserver to Grid and Chart
deephaven/web-client-ui pull request #1626
Opened 2023-11-06 20:30 UTC by mofojed

- ResizeObserver is now widely available in all browsers, so use it to listen for resizing of our grid and plot elements
- Pull `grid-wrapper` from `IrisGrid` and put it directly in `Grid`
  - Now `Grid` doesn't have to listen to the "parent" element, which was kind of strange in the first place.
- Tested by opening up some tables and charts, resizing the panels and ensuring they updated correctly.

2023-11-06 22:04 UTC, mattrunyon requested changes

2023-11-07 15:07 UTC, mofojed commented on packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
>    }
Wasn't going to make that much change for this.

2023-11-07 18:32 UTC, mattrunyon approved these changes

2023-11-07 21:02 UTC, mofojed commented
@mattrunyon updated so you can see the full error message from the UI: 
![image](https://github.com/deephaven/web-client-ui/assets/4505624/9907d271-ed17-468e-b642-4d09a6dd2b6d)

2023-11-07 21:09 UTC, mofojed commented
Right you are - updated the other PR.

2023-11-07 21:09 UTC, merged