fix: `figure_title` and `chart_title` were not mapped up correctly
deephaven/web-client-ui pull request #1676
Opened 2023-12-07 17:28 UTC by mofojed

- Previously for some reason we were mapping the first subplot chart title to the figure title, which was incorrect. Instead map the Figure title attribute to the figure, and then chart title to the individual subplots
- Annoyingly plotly doesn't have a chart title property, so we need to map these titles to `annotations` to get it to work correctly
- Fixes #1674 , Fixes #1675 
- Tested with the following snippet:
```
from deephaven.plot.figure import Figure
from deephaven import read_csv

insurance = read_csv("https://media.githubusercontent.com/media/deephaven/examples/main/Insurance/csv/insurance.csv")

insurance_by_region = insurance.view(formulas=["region", "expenses"]).avg_by(["region"])
insurance_by_sex = insurance.view(formulas=["sex", "expenses"]).avg_by(["sex"])
insurance_by_children = insurance.view(formulas=["children", "expenses"]).avg_by(["children"]).sort(order_by=["children"])
insurance_by_smoker = insurance.view(["smoker", "expenses"]).avg_by(["smoker"])

insurance_cat_plots = Figure(rows=2, cols=2).\
    new_chart(row=0, col=0).\
    plot_cat(series_name="Region", t=insurance_by_region, category="region", y="expenses").\
    chart_title(title="Average charge ($) by region").\
    new_chart(row=0, col=1).\
    plot_cat(series_name="Sex", t=insurance_by_sex, category="sex", y="expenses").\
    chart_title(title="Average charge ($) by sex").\
    new_chart(row=1, col=0).\
    plot_cat(series_name="Children", t=insurance_by_children, category="children", y="expenses").\
    chart_title(title="Average charge ($) per number of children").\
    new_chart(row=1, col=1).\
    plot_cat(series_name="Smoker", t=insurance_by_smoker, category="smoker", y="expenses").\
    chart_title(title="Average charge ($) smokers vs nonsmokers").\
    chart_legend(visible=False).\
    figure_title("Figure Title").\
    show()
```

![image](https://github.com/deephaven/web-client-ui/assets/4505624/f9a6f7fc-3110-492a-8d57-1d49616ce387)

2023-12-08 22:56 UTC, dsmmcken commented
> Previously for some reason we were mapping the first subplot chart title to the figure title, which was incorrect. Instead map the Figure title attribute to the figure, and then chart title to the individual subplots

I think we need to still support this behaviour as that's what our docs said to use, so people have been using chart_title like it was figure_title. Maybe only in the case where figure_title is null or chart_title count == 1 or something.

2023-12-11 21:03 UTC, mattrunyon requested changes

2023-12-18 16:39 UTC, mattrunyon approved these changes
Looks good. Just want to confirm w/ @dsmmcken that the chart title spacing is good (it's consistent now regardless of panel size)

![newplot](https://github.com/deephaven/web-client-ui/assets/8619789/5aae39c0-7832-4417-be84-e9787682b1f2)

2023-12-18 19:47 UTC, dsmmcken commented
Spacing is fine :shipit:

2023-12-19 15:11 UTC, merged