feat: Default Plotly map colors
deephaven/web-client-ui pull request #1721
Opened 2024-01-10 18:22 UTC by bmingles

- Added theme variables for Plotly map colors. Wired them up to the default layout
- Removed unused chart theme variables
- Fixed scroll issue in styleguide

2024-01-12 21:11 UTC, mattrunyon requested changes

2024-01-12 21:11 UTC, mattrunyon commented on packages/chart/src/ChartTheme.module.scss
> +  river-color: var(--dh-color-plotly-geo-river);
I think these should be `--dh-color-chart-geo-*` to match the name pattern of the other variables

2024-01-12 21:11 UTC, mattrunyon commented on packages/chart/src/ChartUtils.ts
> +      // ohlc_decreasing,
Why are these commented out here?

2024-01-12 21:11 UTC, mattrunyon commented on packages/chart/src/ChartUtils.ts
> +
Can you add a jsdoc to this method and include a link to https://plotly.com/javascript/reference/layout/ in it? It doesn't include everything (they're spread under different pages in the sidebar), but gives the starting point at least

2024-01-16 19:31 UTC, mattrunyon commented
@dsmmcken Should we remove the frame? We can control `framecolor`, `framewidth`, and `showframe`

![image](https://github.com/deephaven/web-client-ui/assets/8619789/f861121e-aaba-4511-abba-9fec81fd17a2)

2024-01-16 19:35 UTC, mattrunyon commented on packages/chart/src/ChartUtils.ts
> +        showcoastlines: true,
Need to add `geo.bgcolor`. I'd say just set it to `plot_bgcolor` instead of making a separate variable for it

2024-01-17 15:12 UTC, dsmmcken commented
In your example, I would expect the area inside the red line to have the slightly lighter bg color, and everything outside to have the content-bg color.

Then hiding the frame is fine.

2024-01-17 15:57 UTC, bmingles commented
I set `bgcolor` to `paper_bgcolor` instead of `plot_bgcolor` so that it gets the outer color and keeps the frame boundary as the delineation of the 2 colors

2024-01-18 22:39 UTC, mattrunyon approved these changes

2024-01-18 22:55 UTC, merged