feat: theming tweaks
deephaven/web-client-ui pull request #1727
Opened 2024-01-12 16:52 UTC by dsmmcken

Miscellaneous light and dark theme tweaks after using it for awhile. Mostly things that were either improperly styled or issues for enterprise.

- light disabled color for secondary buttons
- adjust subdued-content-bg defninition
- adjusted dark surface color
- tweaked light theme to be grayer
- added subdued-content-bg variable
- fix button alignment
- style tweaks
- minor color fixes
- style editor in conditional formating style fixes
- fix console button disabled object styling
- Numerous color adjustments
- fix malformed hsl variable
- adjust time slider styling
- fix HCM styling
- fix styling of custom time select
- item-list styling
- add fallback colors for a few more things, so that error message before api works
- Buttons can use gap instead of margin on icons now that they are flex. Much easier.
- whitespace change
- expose is modified styling to styleguide timeslider for checking
- styleguide icon button styling
- add some spectrum stuff to styleguide for easier comparison
- purge primary-light
- schotcut settings rror message styling
- settings menu user image and logo button adjust
- widget list hover color
- add legend color

2024-01-12 18:07 UTC, bmingles commented on packages/components/scss/bootstrap_overrides.scss
> +$input-btn-padding-y: 0.42145rem;
Nice tweak

2024-01-12 18:14 UTC, bmingles commented on packages/components/src/theme/theme-spectrum/theme-spectrum-overrides.css
> +  --dh-table-header-cell-background-color: transparent;
Kudos for introducing this pattern to make it possible to override

2024-01-12 18:16 UTC, bmingles commented on packages/components/src/theme/theme-spectrum/theme-spectrum-overrides.css
> +  /* center the text vertically, we have different font, it requires different centering */
May be worth clarifying that "different font" is with respect to Spectrum's font

2024-01-12 18:22 UTC, bmingles requested changes
Changes look good overall.
- 1 minor suggestion for a comment tweak
- Also 2 styleguide alignment things I noticed with spectrum-forms and spectrum comparison checkbox / radio examples

2024-01-16 15:52 UTC, bmingles submitted a review, later dismissed
LGTM

2024-01-16 17:32 UTC, mofojed submitted a review, later dismissed

2024-01-16 17:50 UTC, mofojed submitted a review, later dismissed

2024-01-16 17:50 UTC, mofojed commented on packages/code-studio/src/styleguide/TimeSliderInputs.tsx
> +        <p style={isStartModified ? { color: 'var(--dh-color-modified)' } : {}}>
Should we be using style tag directly here or a CSS class name and put this in the CSS?

2024-01-16 19:18 UTC, bmingles approved these changes

2024-01-16 19:49 UTC, mofojed approved these changes

2024-01-16 19:49 UTC, merged