refactor: Remove databar code
deephaven/web-client-ui pull request #1758
Opened 2024-01-30 20:05 UTC by mattrunyon

Removing databar specific code since this feature will be moved to dh.ui at some point

2024-01-30 20:42 UTC, dsmmcken commented
> Removing databar specific code since this feature will be moved to dh.ui at some point

We've discussed the pyhon api being on ul.table... the JS would always be needed regardless of where the api originates from.

2024-01-30 21:19 UTC, mofojed requested changes
Just rip the API part out of databars, not the whole UI part (though it will be unused until we do wire it up to API).

Building into deephaven.ui we'll need to extend the model with our data bar options (so where `UITable.tsx` calls `IrisGridModelFactory.makeModel`, we'll need some way to add options in there or extend the model returned or have our own factory function or something).

Side note, in the future having plugins for cell renderers might be neat (customer I met with today was asking about them) but not our top priority.

2024-01-30 21:19 UTC, mofojed commented on packages/iris-grid/src/IrisGridTableModelTemplate.ts
Only changes we need is for `dataBarOptionsForCell` to throw, and remove `formatDataBar` from the `Format` type in dh.types.ts.

2024-01-30 21:36 UTC, mattrunyon commented on packages/iris-grid/src/IrisGridTableModelTemplate.ts
`dataBarOptionsForCell` throws from `IrisGridModel`, so just removing it from the table model template. `renderTypeForCell` returns `text` from `GridModel`, so removing that from the table model template as well

2024-01-31 19:40 UTC, mofojed approved these changes

2024-01-31 20:04 UTC, merged