fix: spectrum textfield validation icon position with set content-box
deephaven/web-client-ui pull request #1825
Opened 2024-02-22 20:29 UTC by dsmmcken

Moves a DHE fix to DHC.

BREAKING CHANGE: the duplicate `spectrum-Textfield-validationIcon` css in DHE should be removed

2024-02-22 20:31 UTC, dsmmcken commented
feels like a bit of an abuse of breaking change, but not sure how else to flag that the DHE code can be removed when this is merged to DHE.

2024-02-22 21:20 UTC, bmingles requested changes
Looks like e2e tests need to be updated

2024-02-22 22:33 UTC, dsmmcken commented
Flaky test failure, re-ran and it passed.

2024-02-23 15:19 UTC, bmingles approved these changes
LGTM. Verified that the icon is positioned correctly in the styleguide y setting `validationState="invalid"`

2024-02-23 15:24 UTC, merged