feat: new chart error panel
deephaven/web-client-ui pull request #1850
Opened 2024-03-05 07:26 UTC by ethanalvizo

Closes #1520

2024-03-05 07:47 UTC, ethanalvizo commented on packages/chart/src/Chart.tsx
> +        {downsamplingError != null && (
wasn't quite sure what the difference is between downsampling errors and other types of errors. Do we not want them to show in this window as well?

Currently I have them trigger their own overlay warning

2024-03-26 20:14 UTC, ethanalvizo commented
<img width="657" alt="image" src="https://github.com/deephaven/web-client-ui/assets/55671206/0aedb6c5-a33e-4f71-a1c1-9827aab5ed92">


New error popup^

2024-03-27 13:44 UTC, mofojed requested changes

2024-03-27 13:44 UTC, mofojed commented on packages/chart/src/ChartErrorOverlay.tsx
> +        {/* )} */}
```suggestion
```

2024-03-27 13:44 UTC, mofojed commented on packages/chart/src/ChartErrorOverlay.tsx
> +        {/* {!undismissableError && ( */}
Remove undismissable commented out code
```suggestion
```

2024-03-27 13:44 UTC, mofojed commented on packages/chart/src/ChartErrorOverlay.tsx
> +    errorMessage === 'Too many items to disable downsampling';
Remove this `undismissableError` part.
```suggestion
```

2024-03-27 13:45 UTC, mofojed approved these changes

2024-04-05 13:40 UTC, mofojed approved these changes

2024-04-05 13:40 UTC, merged