feat: improve table loading
deephaven/web-client-ui pull request #1898
Opened 2024-03-25 14:06 UTC by wusteven815

2024-03-25 14:09 UTC, wusteven815 commented
Didn't use a new event, wired it up to `IrisGridModelUpdater`'s `updateViewport` instead

2024-03-27 17:33 UTC, mofojed requested changes
`iris-grid-loading` element that gets loaded blocks all user interaction while scrolling... also, the `Cancel` button doesn't make sense in this context. It will try and rollback the state of filters etc. which doesn't make sense, and you can't really "cancel" a viewport operation.

Instead, I don't think we should show the cancel button, and we shouldn't stop the user from interacting/scrolling the table either. We just want the loading status in the bottom. So we may need to add another loading state value or something.

2024-03-27 17:33 UTC, mofojed commented on packages/iris-grid/src/IrisGrid.tsx
> +    this.onViewportUpdate = this.onViewportUpdate.bind(this);
Name this `handleViewportUpdate` instead. That's the naming convention that React tends to use in their docs: https://react.dev/learn/responding-to-events
`on*` for the prop name, and then `handle*` for the handler's name.

2024-03-27 17:33 UTC, mofojed commented on packages/iris-grid/src/IrisGridModel.ts
> +
I know I said to name it `hasPendingOperations`, but this is really viewport specific - I'd rename it `isViewportPending` or `isViewportLoading` instead.

2024-03-27 17:33 UTC, mofojed commented on packages/iris-grid/src/IrisGrid.tsx
> +      }, 500);
Set this value as a `const` at the top with the other constants.

2024-03-27 17:33 UTC, mofojed commented on packages/iris-grid/src/IrisGrid.tsx
> +      this.pendingOperationsTimeout = setTimeout(() => {
You'll need to clear this timeout on unmount as well. Similar to my other suggestion, I'd suggest a name `viewportLoadingTimeout` instead.

2024-03-27 17:33 UTC, mofojed commented on packages/iris-grid/src/IrisGridTableModelTemplate.ts
> +  }
We should also check that the columns requested match the columns in the viewport for horizontal scrolling with a large table. 

A table with 100 columns: 
```
from deephaven import empty_table
import time

def f(a):
    time.sleep(0.1)
    return a

t = empty_table(100).update([f"X{c} = i" for c in range(100)]).update_view("Y = f(i)")
```

2024-04-04 13:49 UTC, mofojed requested changes
Just some cleanup/suggestions.

If we wanted to get _really_ fancy, we'd keep a list of the pending operations and their type, then decide what loading text/spinner to display at render time based on all the current pending operations. In theory, this could also help us with our rollback before (right now we just rollback to the last loaded state). I think that's all out of scope for right now though, this is good.

2024-04-04 13:49 UTC, mofojed commented on packages/iris-grid/src/IrisGridModel.ts
> +    VIEWPORT_UPDATED: 'VIEWPORT_UPDATED',
Let's add some JSDocs for this event. In retrospect, we should have them for all of the events, but we can at least be proactive and add some here to make it clear what the event is for. 

When writing good docs for a function, you want to address possible questions a future reader for have; think about what kind of questions a reader of this code (or user of the event) may have. 

For example, is this fired when the set viewport in the model is changed, when the viewport is applied to the table, or when the viewport data has come back? Is there any data included with the event? Another common question is "Why?", as in "Why do we need this event?"
```suggestion

    /** Fired when the viewport is applied to the table and we're waiting for a response. */
    VIEWPORT_UPDATED: 'VIEWPORT_UPDATED',
```

2024-04-04 13:49 UTC, mofojed commented on packages/iris-grid/src/IrisGrid.tsx
> +    }
What you're doing here is throttling the function. This is a pretty common pattern. You can see `handleDownloadProgressUpdate` in this file (or `IrisGridTableModelTemplate.applyViewport`) for an example of a throttled function. But you could rewrite it like this:

```
componentWillUnmount() {
  ...
  // You at least need to stop the timer, you're not doing that currently.
  this.showViewportLoading.cancel();
  ...
}

showViewportLoading = throttle(
  (): void => {
    const { model } = this.props;
    const { loadingSpinnerShown } = this.state;
    if (model.isViewportPending && !loadingSpinnerShown) {
      // We only want to show the viewport loading if the viewport is still loading and we're not already showing a loader for something else
      this.startLoading("Waiting for viewport...", {
        loadingCancelShown: false,
        loadingBlocksGrid: false,
      });
    }
  },
  VIEWPORT_LOADING_DELAY
);


handleViewportUpdated(): void {
  this.showViewportLoading();
}

handleUpdate() {
  ...
  this.showViewportLoading.cancel();
  ...
}
```

2024-04-11 13:33 UTC, mofojed approved these changes
Great work!

2024-04-11 13:49 UTC, merged