fix: change fira source
deephaven/web-client-ui pull request #1944
Opened 2024-04-17 17:16 UTC by wusteven815

2024-04-18 14:00 UTC, mofojed commented
@dsmmcken would these differences be expected/okay? Fonts appear okay to me, tabular numbering etc.

**Actual:**
![typography-actual](https://github.com/deephaven/web-client-ui/assets/4505624/6a8a18e8-bc96-4304-a922-f3e65ecf172c)

**Expected:**
![typography-expected](https://github.com/deephaven/web-client-ui/assets/4505624/3208da70-28b0-4d48-a3e1-e4552d321824)

**Diff:**
![typography-diff](https://github.com/deephaven/web-client-ui/assets/4505624/ecd4c699-7930-4c27-9daa-7e3b47d3fcf0)


From in the app on a table with numbers:
![image](https://github.com/deephaven/web-client-ui/assets/4505624/db01141b-0680-4088-8a46-b74990ed910c)

2024-04-18 14:08 UTC, dsmmcken submitted a review, later dismissed
Missing `Fira Mono`, which is being substituted. The previous package included both Fira Sans and Mono, you'll have to add those in as well.

That's frustrating that the kerning tables must be different. Still looks acceptable, and has correct font-features-settings. 🤷

2024-04-18 14:30 UTC, dsmmcken commented
![null](https://github.com/deephaven/web-client-ui/assets/1576283/5bca3103-9411-4e6a-a16e-4bf1410ba60d)

We are probably also missing an italic version in that weight.

2024-04-24 19:04 UTC, dsmmcken commented on packages/app-utils/src/components/FontBootstrap.tsx
> +import '@fontsource/fira-sans/700.css';
```suggestion
import '@fontsource/fira-sans/300.css';
import '@fontsource/fira-sans/300-italic.css';
import '@fontsource/fira-sans/400.css';
import '@fontsource/fira-sans/400-italic.css';
import '@fontsource/fira-sans/500.css';
import '@fontsource/fira-sans/600.css';
import '@fontsource/fira-sans/700.css';
import '@fontsource/fira-sans/700-italic.css';
```

There's a couple places with 300 italic and 700 italic

2024-04-25 14:50 UTC, dsmmcken approved these changes

2024-04-26 13:19 UTC, mofojed approved these changes

2024-04-26 13:39 UTC, mofojed requested changes
Need to re-run `npm install` to update the `package-lock.json` now.

2024-04-26 17:29 UTC, dsmmcken approved these changes

2024-04-26 17:30 UTC, merged