fix: Fix null partition filter
deephaven/web-client-ui pull request #1954
Opened 2024-04-22 13:55 UTC by vbabich

Closes #1867

2024-04-22 16:54 UTC, mofojed requested changes
Minor display string change, can you also include how this was tested in the PR description?

2024-04-22 16:54 UTC, mofojed commented on packages/iris-grid/src/IrisGridPartitionSelector.tsx
> +      return 'null';
We display it as `(null)` in other places (like DropdownFilter, CSV export).

2024-04-23 17:42 UTC, vbabich commented
Changed `null` to `(null)`, added testing steps to the description.

2024-04-23 18:21 UTC, vbabich commented
I tested this in a Core+ worker and it looks like the api returns `undefined` for a `null` partition key value. Will need to investigate a bit more.

2024-04-23 20:35 UTC, vbabich commented
Partitioned table with a `null` key in DHE:

![Screenshot 2024-04-23 at 11 34 44 AM](https://github.com/deephaven/web-client-ui/assets/2853653/01d182cb-586a-40df-80a1-b152a41e5245)



DHC shows an extra empty `option` element until the [core PR](https://github.com/deephaven/deephaven-core/issues/5400) is merged.

![Screenshot 2024-04-23 at 2 14 57 PM](https://github.com/deephaven/web-client-ui/assets/2853653/010e897a-aa44-4f48-b272-860577393907)

2024-04-23 23:21 UTC, vbabich commented
Added nullish coalescing to account for `undefined` returned by the JSAPI for `null` table values

2024-04-24 15:15 UTC, mofojed approved these changes
Minor suggestion to include the core ticket number.

2024-04-24 15:15 UTC, mofojed commented on packages/iris-grid/src/IrisGrid.tsx
> +            // Core JSAPI returns undefined for null table values, IrisGridPartitionSelector expects null
Add the ticket number
```suggestion
            // Core JSAPI returns undefined for null table values, IrisGridPartitionSelector expects null (https://github.com/deephaven/deephaven-core/issues/5400)
```

2024-04-24 17:26 UTC, mofojed approved these changes

2024-04-24 19:33 UTC, merged