feat: ListView + Picker - Item icon support
deephaven/web-client-ui pull request #1959
Opened 2024-04-23 22:22 UTC by bmingles

2024-04-30 13:21 UTC, mofojed requested changes
Some docs clean up will help, also question about UIConstants which may warrant a follow up.

2024-04-30 13:21 UTC, mofojed commented on packages/components/src/spectrum/utils/itemWrapperUtils.tsx
> +        {content === '' ? NON_BREAKING_SPACE : String(content)}
Comment about why the nbsp here

2024-04-30 13:45 UTC, bmingles commented on packages/code-studio/src/styleguide/ListViews.tsx
> +import { LIST_VIEW_ROW_HEIGHTS } from '@deephaven/utils';
I believe this module was created before the UI work really started as part of moving some ACL utils to DHC. Looks like all but `SPELLCHECK_FALSE_ATTRIBUTE` could be moved to @deephaven/components

2024-04-30 17:08 UTC, bmingles commented
@mofojed I addressed your comments. I also had to fix an issue in the styleguide
- Added back the content height check to only render ListView when container is visible
- Added a fail quick check to detect console errors in styleguide tests

2024-05-01 13:36 UTC, mofojed approved these changes

2024-05-01 13:37 UTC, merged