chore: Downgrade Spectrum to 3.33.1
deephaven/web-client-ui pull request #1978
Opened 2024-05-01 15:48 UTC by bmingles

Downgraded Spectrum to 3.33.1 to fix Combobox scrolling.

resolves #1976

2024-05-01 18:18 UTC, dsmmcken requested changes
Version bump only. Don't do extra stuff in this PR.

2024-05-01 18:22 UTC, bmingles commented on packages/code-studio/src/styleguide/SpectrumComparison.tsx
> +const options = createOptions();
was trying to avoid having to change e2e snapshot, but that's fair. I may just remove it since it didn't produce the original problem anyway

2024-05-01 19:16 UTC, dsmmcken approved these changes

2024-05-01 19:18 UTC, merged

2024-05-03 20:46 UTC, bmingles commented
@mofojed I changed the title to `fix`. I don't see this in the release notes. Did you update it?