feat: ComboBox - @deephaven/jsapi-components
deephaven/web-client-ui pull request #2077
Opened 2024-06-13 14:53 UTC by bmingles

resolves #2074

2024-06-27 18:54 UTC, bmingles commented on packages/jsapi-components/src/spectrum/utils/usePickerProps.ts
> +  const { data: tableCopy } = usePromiseFactory(
@mofojed for reference, I think this is where we could apply addition filters as part of @AkshatJawne partition table work

2024-06-27 18:58 UTC, bmingles commented on packages/jsapi-components/src/spectrum/utils/usePickerProps.ts
> +  const { data: tableCopy } = usePromiseFactory(
I guess it might make sense to just add it to this PR, but I'm fine either way

2024-07-03 12:51 UTC, mofojed approved these changes

2024-07-03 12:54 UTC, mofojed requested changes
Only thing that needs updating is the PR description
Show passing in a `ui.item_table_data_source` instead of passing in props for `key_column` directly on `combo_box`.

2024-07-03 14:19 UTC, mofojed approved these changes

2024-07-03 14:21 UTC, merged