fix: Dashboard plugin crashing UI on throw
deephaven/web-client-ui pull request #2080
Opened 2024-06-13 21:32 UTC by AkshatJawne

Resolves https://github.com/deephaven/web-client-ui/issues/1771

**Changes Implemented:** 
- Wrap `ErrorBoundary` around each Dashboard Plugin in `getDashboardPlugins` (the function that is responsible for getting `dashboardPlugins` in `AppMainContainer.tsx`)

2024-06-13 21:53 UTC, AkshatJawne commented
Will look into failures here

2024-06-14 16:37 UTC, AkshatJawne commented
Will remove commented out code if approach works

2024-06-14 20:02 UTC, mattrunyon requested changes
Update the PR body as well. Looks like what you listed was the original fix attempt

2024-06-14 20:02 UTC, mattrunyon commented on packages/dashboard/src/DashboardLayout.tsx
> +          <ErrorBoundary fallback={[]}>
Add a comment that the fallback is so we do not show the error message over the entire app and we should do something like a toast message w/ the error in the future

2024-06-17 18:57 UTC, mattrunyon approved these changes
Looks good. Also at least prevents the crash in https://github.com/deephaven/deephaven-plugins/issues/510 but that ticket still documents bad behavior in Deephaven UI, so it should stay open

2024-06-17 19:11 UTC, merged