fix: DH-17292 Handle disconnect from GridWidgetPlugin
deephaven/web-client-ui pull request #2086
Opened 2024-06-20 15:01 UTC by mofojed

- When the model is disconnected, we should just display an error. There's no option to reconnect, as the widget schema could change entirely
- By unloading the IrisGrid component, it's no longer throwing an error by trying to access table methods after a table.close()
- Fixes DH-17292 from Enterprise
  - Tested using the steps in the description

2024-06-20 20:22 UTC, mattrunyon reviewed
Does this need to be fixed with `ChartWidgetPlugin` too? I'd guess yes since it has basically the same setup as `GridWidgetPlugin`

2024-06-20 20:22 UTC, mattrunyon commented on packages/dashboard-core-plugins/src/GridWidgetPlugin.tsx
> +        setError(new Error('Model disconnected'));
Just curious if we maybe want this to say `Table disconnected` which might be slightly more user friendly?

2024-06-20 20:23 UTC, mattrunyon commented
And possibly `PandasWidgetPlugin`, but not sure if that model emits disconnects

2024-06-21 14:29 UTC, mofojed commented
Having a hard time debugging the Pandas thing because of a Pandas Enterprise issue: https://deephaven.atlassian.net/issues/DH-17081
I'll submit a fix for that first...

2024-07-04 12:59 UTC, mofojed commented
Now that we no longer show the widget after a disconnect/error (https://github.com/deephaven/deephaven-plugins/pull/585) this PR is no longer relevant and will be closed.

2024-07-04 13:01 UTC, mofojed commented
Actually I realized there's some refactoring here (`useIrisGridModel`) which cleans some things up and could still be merged, so keeping it open.

2024-07-06 05:36 UTC, mattrunyon requested changes

2024-07-06 05:36 UTC, mattrunyon commented on packages/dashboard-core-plugins/src/useIrisGridModel.test.ts
> +});
Should also add a few tests for reload lifecycle. I.e. reload goes to loading state, then success or reload goes to loading then failure

2024-08-21 05:00 UTC, mattrunyon approved these changes

2024-08-27 13:35 UTC, merged