fix: Partition Table not rendering with additional non key columns
deephaven/web-client-ui pull request #2096
Opened 2024-06-21 17:13 UTC by AkshatJawne

Resolves https://github.com/deephaven/web-client-ui/issues/2066

This PR is solely to solve the bugs of the partition table; first that the widget was not appearing, and once appearing, the partition selectors not working properly. The PartitionTable design changes and additional functionality specified in https://github.com/deephaven/web-client-ui/issues/2079  will be brought up in another PR. This is to keep a clear demarcation between debugging an existing problem and modifying the design to enhance the component.

_Existing Core PR that will be needed as part of refactoring:_ https://github.com/deephaven/deephaven-core/pull/5645

**Steps moving forward:**
- There is no way on the UI for us to differentiate between a _Partition-Aware Source Table_ and a _Partitioned Table_ since there is no method from the JSAPI that would allow us to differentiate between the two (and the config on the Web-side is identical); unless we get a method like this, we will not be able to have different titles, different context menu actions, etc.

   --->  ie. I think we would need something similar `isPartitionRequired` , which would allow us to have ternary conditions to differentiate between the two

2024-06-25 19:09 UTC, mattrunyon requested changes

2024-06-25 19:09 UTC, mattrunyon commented on packages/iris-grid/src/IrisGridPartitionSelector.tsx
> +        </div>
This leaves a weird divider on the left side when it's not a partitioned table. Why the empty string?

It looks like the epic ticket says to just remove this label

2024-06-26 19:17 UTC, mattrunyon commented
I think your e2e tests might be failing due to a core change. Looks like it's failing to apply date filters

2024-06-26 19:18 UTC, AkshatJawne commented
Hmm interesting, I guess I will try and pull the newest version of main?

2024-06-26 19:19 UTC, AkshatJawne commented
I do see that is due to a screenshot, but I thought that it may be due to the change in the Partition Table label that I made here

2024-06-26 21:55 UTC, mattrunyon requested changes
Ok so looks like `IrisGridPartitionSelector.scss` needs some modification. There's still the divider line to the left of the buttons on the left side of this image
![image](https://github.com/deephaven/web-client-ui/assets/8619789/ae553df8-312c-49a5-a670-45f8f8e4b3ec)

Looks like you need to change `.partition-button-group` for `border-style` to `border-right-style: solid` . And then `padding` to `padding-right: $spacer-2`

2024-06-26 21:57 UTC, mattrunyon commented
Also, if this is the PR that fixes the linked ticket (there are 2 and I think this is the real one as the other PR just includes these commits right now) then change the title to `fix: DH-17242: Partition...`. That way when we update the web package versions in enterprise, we see the Jira ticket in the changelog and know to update its status

2024-06-27 16:45 UTC, mattrunyon requested changes

2024-06-27 16:45 UTC, mattrunyon commented on packages/iris-grid/src/IrisGridPartitionSelector.scss
>      padding: 0 $spacer-2;
Need to change the `padding` too. There's too much gap on the left with this padding. Should just be `padding-right: $spacer-2`

2024-06-27 17:10 UTC, mattrunyon approved these changes

2024-06-27 17:15 UTC, AkshatJawne commented
Will hold off on merging until we can add filter prop to the Picker component, to avoid having to set the viewport on each render to 0,50 -- @bmingles mentioned that will have to wait for #2077 to merge before making these changes.

2024-06-27 17:17 UTC, mattrunyon requested changes
Switching to request changes so it doesn't get accidentally merged

2024-07-17 18:15 UTC, AkshatJawne commented
Closing this PR given that we are no longer opting to manually set the viewport to 0,50 -- and we ultimately did not add a filter prop to Picker, but rather changed how the options are populated in the pickers.

Refer to https://github.com/deephaven/web-client-ui/pull/2110 for all details and updated changes

2024-07-17 18:15 UTC, closed without merging