fix: TablePlugin needs to know table name and selected range
deephaven/web-client-ui pull request #2181
Opened 2024-08-07 14:08 UTC by AkshatJawne

Resolves #2093

2024-08-12 13:24 UTC, AkshatJawne reviewed
@mofojed I just passed the `tableName` and `selectedRanges` props down to the plugin, was there anything specific you were wanting here, in terms of a "better way" to handle the prop?

2024-08-15 17:55 UTC, mofojed requested changes

2024-08-15 17:55 UTC, mofojed commented on packages/dashboard-core-plugins/src/panels/IrisGridPanel.tsx
> -
Let's continue to leave this in for now - now that there's a replacement, they have a version to replace the deprecated properties with the new options we're providing.

2024-08-15 17:58 UTC, AkshatJawne reviewed
Ready for re-review @mofojed

2024-08-15 18:34 UTC, mofojed approved these changes

2024-08-15 18:38 UTC, merged