feat: add monaco docs CSS override
deephaven/web-client-ui pull request #2250
Opened 2024-10-07 14:50 UTC by wusteven815

2024-10-07 15:01 UTC, wusteven815 commented
- `min-width` - it should have a min width to avoid looking thin
- `hr` - make horizontal breaks visible
- `blockquote` - make block quotes have a margin to make them indented

2024-10-08 16:28 UTC, dsmmcken submitted a review, later dismissed

2024-10-08 16:28 UTC, dsmmcken commented on packages/console/src/ConsoleInput.scss
> +.docs {
That's a pretty greedy selector, and not scoped. Where is ".docs" as the class defined?

I think Editor.css is probably a better place for this as well.

2024-10-08 16:28 UTC, dsmmcken commented on packages/console/src/ConsoleInput.scss
> +  min-width: 200px;
```suggestion
  min-width: 12rem;
```

2024-10-08 16:28 UTC, dsmmcken commented on packages/console/src/ConsoleInput.scss
> +    margin-left: 20px;
```suggestion
    margin-left: $spacer-3;
```

Or spacer-2 whichever is closer.

2024-10-15 18:02 UTC, wusteven815 commented on packages/console/src/notebook/Editor.scss
> +.rendered-markdown.markdown-docs {
Yes, this is the selector for single element with `.rendered-markdown` and `.markdown-docs` classes

2024-10-15 20:14 UTC, dsmmcken approved these changes

2024-10-15 20:15 UTC, dsmmcken requested changes
Actually, one last thing. Comment what this is for. In future I could see a case of someone searching this codebase and not finding any matches for it so it could accidentally get deleted without knowing it originates elsewhere.

2024-10-16 17:48 UTC, dsmmcken commented on packages/console/src/notebook/Editor.scss
> +// Override Monaco's default markdown popups (i.e signature help) to resemble VS Code closer
Please specifically mention that this class is defined in core or wherever.

2024-10-16 18:54 UTC, dsmmcken approved these changes

2024-10-17 14:21 UTC, merged