do not collapse console errors on mouseUp
deephaven/web-client-ui pull request #275
Opened 2021-11-03 19:03 UTC by spasovski

fixes #192 

This was clearly intentionally allowed before but I agree the new behaviour is better.

2021-11-09 12:35 UTC, mofojed requested changes
Don reviewed this for UX? You can't select the first line of the exception, we need to be able to select the full exception.

2021-11-09 14:25 UTC, dsmmcken commented
true, not sure it's any better, it just shifted the problem from the body to the button.

2021-11-09 16:04 UTC, spasovski commented
The button text is selectable (though not easily) - I'd float a copy to clipboard button to the far right of the error expand button and we can manually write the full text to the clipboard.

2021-11-10 16:44 UTC, mofojed commented
You can't select the button/top line of text at all right now? A floating copy button might be handy for copying a particular exception, but you should also just be able to copy the console output in general (eg. if you have a bunch of logging lines, then an exception, more logging, you should be able to select all that).

2021-11-10 19:21 UTC, mofojed requested changes

2021-11-10 19:21 UTC, mofojed commented on packages/console/src/console-history/ConsoleHistoryResultErrorMessage.jsx
> +          <button
Keep this in a div so you can select text.

Check behaviour in Firefox to ensure right-click does not trigger.

2021-11-11 23:00 UTC, mofojed requested changes

2021-11-11 23:00 UTC, mofojed commented on packages/console/src/console-history/ConsoleHistoryResultErrorMessage.jsx
> +              className={arrowBtnClasses}
This looks much better! Only issue is that the button doesn't highlight when you are hovering over it itself.

Could add this here:
```
            onMouseEnter={this.handleMouseEnter}
            onMouseLeave={this.handleMouseLeave}
```
Or just add a `error-message.btn:hover` styling as well

2021-11-11 23:16 UTC, mofojed approved these changes

2021-11-12 19:23 UTC, mofojed approved these changes

2021-11-12 19:28 UTC, merged