DH-11923: Fix column tooltip when above the table
deephaven/web-client-ui pull request #306
Opened 2021-11-19 21:19 UTC by dsmmcken

When column tooltips are displayed above the table, instead of below (due to being to close to the bottom edge of the window) attempting to mouse into them was triggering them to close.

![685c7c7f-549a-44a9-9433-06ceb60769fe](https://user-images.githubusercontent.com/1576283/142664186-805c6470-5368-4ab2-a84b-5eb40ef5c1e6.png)

This was caused by IrisGridColumnTooltipMouseHandler triggering its own onLeave even when y < 0  that dismissed the tooltip.

This handler is actually unnecessary now, as the popper has its on move handler on the window, that handles dismissing when the mouse moves outside the bounds of the popper OR **the parent** of the popper. And the parent in this case is a wrapper div that is temporarily created by iris gird to place the popper, and is sized exactly to the column header, and is all that is needed to handle leave events.

![image](https://user-images.githubusercontent.com/1576283/142664603-377b25e2-593e-4efc-b463-da7fafc7b00a.png)

[IN PROGRESS FIXING POSITION]

2021-11-23 21:04 UTC, mofojed requested changes

2021-11-23 21:04 UTC, mofojed commented on packages/iris-grid/src/IrisGrid.jsx
> +       * otherwise the arrow wants to esacpe the boundry.
```suggestion
       * otherwise the arrow wants to escape the boundary.
```

2021-11-23 21:17 UTC, dsmmcken commented on packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
> +    return 3;
how about just Number(name)

2021-11-23 21:26 UTC, mofojed commented on packages/code-studio/src/styleguide/MockIrisGridTreeModel.js
> +    return 3;
Ya sure

2021-11-23 21:27 UTC, mofojed approved these changes

2021-11-23 21:27 UTC, mofojed commented
You'll probably need to rebase so coverage tests don't fail

2021-11-24 14:23 UTC, mofojed approved these changes

2021-11-24 14:30 UTC, merged