tree table snapshots WIP
deephaven/web-client-ui pull request #337
Opened 2021-12-07 22:21 UTC by spasovski

missing formatting and I don't think the intersection is quite right but it's quite the snack

2021-12-08 19:10 UTC, mofojed requested changes

2021-12-08 19:10 UTC, mofojed commented on packages/iris-grid/src/IrisGridTreeTableModel.js
> +      const row = this.viewportData.rows[i];
You'll need to iterate through the columns as well, e.g.
```
  const resultRow = [];
  const viewportRow = this.viewportData.rows[i - this.viewportData.offset];
  for (let j = intersection.startColumn; j <= intersection.endColumn; j += 1) {
    resultRow.push(formatValue(viewportRow.data.get(j).value, this.columns[j]));
  }
  result.push(resultRow);
}
```

2021-12-08 19:10 UTC, mofojed commented on packages/iris-grid/src/IrisGridTreeTableModel.js
> +    for (let i = intersection.startRow; i < intersection.endRow; i += 1) {
Needs to be `i <= intersection.endRow`, as the index is inclusive

2021-12-08 19:10 UTC, mofojed commented on packages/iris-grid/src/IrisGridTreeTableModel.js
> +  snapshot(ranges) {
This still needs to be async, it needs to match the signature of the super IrisGridTableModel
Side note IrisGridModel should update the signature to match IrisGridTableModel as well

2021-12-08 19:10 UTC, mofojed commented on packages/iris-grid/src/IrisGridTreeTableModel.js
> +  textSnapshot(
I don't think you need to override `textSnapshot` if you're override `snapshot`

2021-12-08 19:55 UTC, spasovski commented on packages/iris-grid/src/IrisGridTreeTableModel.js
> +        for (
It's linear time just trust me...

2021-12-08 20:11 UTC, mofojed requested changes

2021-12-10 21:39 UTC, mofojed approved these changes

2021-12-13 04:09 UTC, merged