Don't trigger console csv upload overlay if dragging text
deephaven/web-client-ui pull request #344
Opened 2021-12-09 21:17 UTC by dsmmcken

- You can select text and drag it in a browser (kind == "string"), this shouldn't trigger the csv overlay
- Fix Button component proptype error with "type" other than button requiring an onClick function ex. (csv overlay bar, type=submit)
- Multiple file error should return, as filetype error can replace it

2021-12-10 14:48 UTC, mofojed requested changes

2021-12-10 14:48 UTC, mofojed commented on packages/components/src/Button.tsx
> +  onClick?: React.MouseEventHandler<HTMLButtonElement>;
Right now you could pass `type='button'` and `onClick=undefined` and TypeScript wouldn't report an error - you'd only get an error at run time with prop types.

You'd need to add another interface that extends this, and then use that with `ButtonWithChildren` and `IconOnlyButton` I think. Eg.

```
interface ButtonButtonProps extends BaseButtonProps {
  type?: 'button';
  onClick: React.MouseEventHandler<HTMLButtonElement>;
}

interface SubmitButtonProps extends BaseButtonProps {
  type: 'reset' | 'submit';
  onClick: undefined;  // I think? Or omit if we still want to allow onClick with submit/reset types
}

interface ButtonWithTypeProps = ButtonButtonProps | SubmitButtonProps;

interface ButtonWithChildren extends ButtonWithTypeProps { ... }
interface IconOnlyButton extends ButtonWithTypeProps { ... }

```

2021-12-10 21:43 UTC, dsmmcken commented
Uh, just trying to make both defaultProps and typescript to work together for the type field, and extend the default react button types for everything else.

2021-12-14 20:07 UTC, mofojed approved these changes

2021-12-14 20:16 UTC, merged