Upgrade to TypeScript 4.5
deephaven/web-client-ui pull request #379
Opened 2022-01-12 00:09 UTC by mattrunyon

Fixes #352 

Also moves the TS dependency to the root only since the packages all depend on the root TS version unless otherwise specified (which is no other packages right now)

2022-01-14 14:40 UTC, mofojed approved these changes

2022-01-14 18:47 UTC, mattrunyon commented
We could add a util method like `asError(e: unknown): Error` that turns any non-Error value into the message of the Error returned. If it's already an error just return as is. Then make sure the `onError` always calls w/ an error by using the util

2022-01-14 22:40 UTC, mofojed commented
@mattrunyon The message of the error returned? So like `${e}` or something?

2022-01-14 22:45 UTC, mattrunyon commented
@mofojed Ya I guess it would be something like

```typescript
asError(e: unknown): Error {
  if (e instanceof Error) {
    return e;
  }
  return new Error(`${e}`);
}
```

2022-01-18 16:20 UTC, mofojed requested changes

2022-01-18 16:20 UTC, mofojed commented on packages/utils/src/ErrorUtils.ts
> +export function asError(e: unknown): Error {
Just put this in Grid.tsx for now, do not add the dep between @deephaven/grid and @deephaven/utils

2022-01-18 20:08 UTC, mofojed approved these changes

2022-01-18 20:15 UTC, merged