Run type checks from root
deephaven/web-client-ui pull request #388
Opened 2022-01-18 18:55 UTC by mattrunyon

This runs type checks from the root of the repo to improve performance.

Locally went from ~300s CPU time for a build to ~200s.

It also should improve the start time of `npm start` since the type checking is cached

2022-01-25 16:01 UTC, mofojed requested changes

2022-01-25 16:03 UTC, mofojed commented
I'm getting an error when I run `npm start`:

```
@deephaven/code-studio: ℹ ｢wds｣: Project is running at http://192.168.86.167/
@deephaven/code-studio: ℹ ｢wds｣: webpack output is served from 
@deephaven/code-studio: ℹ ｢wds｣: Content not from webpack is served from /home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/code-studio/public
@deephaven/code-studio: ℹ ｢wds｣: 404s will fallback to /
@deephaven/code-studio: Starting the development server...
[10:59:23 a.m.] Found 0 errors. Watching for file changes.

@deephaven/code-studio: Failed to compile.
@deephaven/code-studio: /home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/code-studio/src/log/LogExport.ts
@deephaven/code-studio: TypeScript error in /home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/code-studio/src/log/LogExport.ts(3,16):
@deephaven/code-studio: Output file '/home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/jsapi-shim/dist/index.d.ts' has not been built from source file '/home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/jsapi-shim/src/index.ts'.  TS6305
@deephaven/code-studio:     1 | /* eslint-disable import/prefer-default-export */
@deephaven/code-studio:     2 | import JSZip from 'jszip';
@deephaven/code-studio:   > 3 | import dh from '@deephaven/jsapi-shim';
@deephaven/code-studio:       |                ^
@deephaven/code-studio:     4 | import { store } from '@deephaven/redux';
@deephaven/code-studio:     5 | import { logHistory } from './LogInit';
@deephaven/code-studio:     6 |

```

2022-01-26 00:21 UTC, mattrunyon commented on packages/chart/src/ChartModelFactory.js
> +   * @returns {Promise<ChartModel | FigureChartModel>} The FigureChartModel representing the figure
Added comment about CRA type checking JS

2022-01-26 00:21 UTC, mattrunyon commented on packages/code-studio/src/main/WidgetUtils.ts
> +    return ChartModelFactory.makeModel(settings as any, figure);
Ya it was the easiest fix for now. W/ our tsconfig CRA was just ignoring type checks for a while

2022-01-26 00:24 UTC, mattrunyon commented on examples/component-template/package.json
> +    "clean:types": "tsc -b --clean",
Ya it's only an option in `build` mode. It determines what files would be created by `tsc --build` including the buildinfo cache file and then deletes them all

2022-01-27 20:45 UTC, mofojed approved these changes

2022-01-27 21:12 UTC, merged