upgrade react to v17
deephaven/web-client-ui pull request #411
Opened 2022-02-01 22:46 UTC by spasovski

fixes #385 

I expect this to be benign based on the release notes but I welcome additional testing by anyone else.

2022-02-03 13:54 UTC, mofojed requested changes
code-studio/package.json was not updated to the correct version of react. After updating that, be sure to run an `npm run clean`, `npm install` to make sure all the package-locks are correct.

Also need to update `@types/react` across all packages to be v17

2022-02-10 21:25 UTC, mofojed approved these changes

2022-02-10 21:25 UTC, mofojed commented on packages/chart/package.json
> +    "react": "^17.x"
Not caused by you, but we should probably be consistent with our peer dependencies format. In some places we do `^17.x`, in others we do `^17.0.0` ... I think I prefer the latter, but I leave that as an exercise for another time.

2022-02-14 20:49 UTC, vbabich approved these changes
Unit tests run without errors, smoke-tested the IU functionality - all looks good. 👍

2022-02-16 12:42 UTC, merged