Remove dependency on jszip from @deephaven/console
deephaven/web-client-ui pull request #548
Opened 2022-05-02 21:18 UTC by mofojed

Instead, now you pass in `unzip` as a prop.

Fixes #547

2022-05-06 21:19 UTC, mattrunyon requested changes

2022-05-10 15:38 UTC, mattrunyon approved these changes

2022-05-10 15:54 UTC, vbabich approved these changes

2022-05-10 20:09 UTC, mofojed commented on packages/code-studio/src/main/AppMainContainer.jsx
> +          <ConsolePlugin hydrateConsole={AppMainContainer.hydrateConsole} />
The reason I didn't do that is in case we add more `hydrate` functions for the other panels later (like `hydrateLog` for example)

2022-05-10 20:09 UTC, merged