Don't check outside of min/max column bounds for groupings
deephaven/web-client-ui pull request #705
Opened 2022-08-03 20:29 UTC by mofojed

- Was checking column indices < 0 and >= columnCount for groups which is invalid

NOTE: This doesn't seem to fix all issues of fetching invalid column indexes for groups. To test, set the `textForColumnHeader` to hit a debugger if it gets asked for an invalid column:
```
  textForColumnHeader(x: ModelIndex, depth = 0): string | undefined {
    const column = this.columnAtDepth(x, depth);
    if (column == null) {
      debugger;
      return undefined;
    }
    return column.name ?? undefined;
  }
```
Tested with this snippet (added `table5` which doesn't have frozen columns):
```
from deephaven import new_table
from deephaven.column import string_col, char_col, int_col

groups = [
    {'name': 'MyShorts', 'children': ['Short', 'Short2', 'Short3']},
    {'name': 'MyInts', 'children': ['Int2', 'Int3'], 'color': 'blue'}
]

groups2 = [
    {'name': 'MegaGroup', 'children': ['MyShorts', 'MyInts', 'Char5']},
    {'name': 'MyShorts', 'children': ['Short', 'Short2', 'Short3']},
    {'name': 'MyInts', 'children': ['Int2', 'Int3'], 'color': 'blue'}
]

groups3 = [
    {'name': 'MegaGroup', 'children': ['MyShorts', 'MyInts', 'Char5']},
    {'name': 'MyShorts', 'children': ['Short', 'Short2', 'Short3']},
    {'name': 'MyInts', 'children': ['Int2', 'Int3'], 'color': 'blue'},
    {'name': 'MoreInts', 'children': ['Int4', 'Int6'], 'color': 'blue'},
    {'name': 'SuperMegaGroup', 'children': ['MegaGroup', 'Char9', 'MoreInts']},
]

table = new_table([
    string_col("Short", ["A" , "B", "C", "D"]),
    char_col("Char", "ABCD"),
    int_col("Int", [123456789, 234567890, 42, 8675309]),
    string_col("Short2", ["A" , "B", "C", "D"]),
    char_col("Char2", "ABCD"),
    int_col("Int2", [123456789, 234567890, 42, 8675309]),
    string_col("Short3", ["A" , "B", "C", "D"]),
    char_col("Char3", "ABCD"),
    int_col("Int3", [123456789, 234567890, 42, 8675309]),
    string_col("Short4", ["A" , "B", "C", "D"]),
    char_col("Char4", "ABCD"),
    int_col("Int4", [123456789, 234567890, 42, 8675309]),
    string_col("Short5", ["A" , "B", "C", "D"]),
    char_col("Char5", "ABCD"),
    int_col("Int5", [123456789, 234567890, 42, 8675309]),
    string_col("Short6", ["A" , "B", "C", "D"]),
    char_col("Char6", "ABCD"),
    int_col("Int6", [123456789, 234567890, 42, 8675309]),
    string_col("Short7", ["A" , "B", "C", "D"]),
    char_col("Char7", "ABCD"),
    int_col("Int7", [123456789, 234567890, 42, 8675309]),
    string_col("Short8", ["A" , "B", "C", "D"]),
    char_col("Char8", "ABCD"),
    int_col("Int8", [123456789, 234567890, 42, 8675309]),
    string_col("Short9", ["A" , "B", "C", "D"]),
    char_col("Char9", "ABCD"),
    int_col("Int9", [123456789, 234567890, 42, 8675309]),
    string_col("Short10", ["A" , "B", "C", "D"]),
    char_col("Char10", "ABCD"),
    int_col("Int10", [123456789, 234567890, 42, 8675309]),
    string_col("Short11", ["A" , "B", "C", "D"]),
    char_col("Char11", "ABCD"),
    int_col("Int11", [123456789, 234567890, 42, 8675309]),
    string_col("Short12", ["A" , "B", "C", "D"]),
    char_col("Char12", "ABCD"),
    int_col("Int12", [123456789, 234567890, 42, 8675309]),
])

table2 = table.layout_hints(freeze=["Char", "Int"], column_groups=groups)
table3 = table2.layout_hints(freeze=["Char", "Int"], column_groups=groups2)
table4 = table3.layout_hints(freeze=["Char", "Int"], column_groups=groups3)
table5 = table.layout_hints(column_groups=groups)
```

2022-08-18 17:47 UTC, mattrunyon requested changes

2022-08-18 17:47 UTC, mattrunyon commented on packages/grid/src/GridRenderer.ts
> +            nextColumnIndex < columnCount &&
```suggestion
            nextColumnIndex < columnCount - 1 &&
```

2022-08-23 18:41 UTC, mofojed commented on packages/grid/src/GridRenderer.ts
> +            nextColumnIndex < columnCount &&
No it shouldn't

2022-08-23 18:43 UTC, mattrunyon approved these changes

2022-08-23 18:44 UTC, merged