Downgrading monaco-editor to v0.31.1
deephaven/web-client-ui pull request #785
Opened 2022-09-28 22:39 UTC by mofojed

- Fixes #773  being unable to escape the suggestion widget
- I don't know what change introduced the issue, as it's not reproducible in v0.34.0 playground and it's just in our code for some reason

I went down a rabbit hole debugging this...
The issue is that container is null when initializing the suggest widget contextview: https://github.com/microsoft/vscode/blob/0c22a33a9d670a84309447b36abdbd8c04ee6219/src/vs/base/browser/ui/contextview/contextview.ts#L162
Because it is null, this listener never gets registered: https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/contextview/contextview.ts#L183
Subsequently, this.hide() never gets called: https://github.com/microsoft/vscode/blob/0c22a33a9d670a84309447b36abdbd8c04ee6219/src/vs/base/browser/ui/contextview/contextview.ts#L352
I don't know how it's supposed to work since the container is always null for that service: https://github.com/microsoft/vscode/blob/0c22a33a9d670a84309447b36abdbd8c04ee6219/src/vs/editor/standalone/browser/standaloneLayoutService.ts#L27
I don't understand why this works in the Playground. I'm missing something, but for now I'm just going to roll back to v0.31.1 which doesn't have this issue.

2022-09-30 20:58 UTC, mattrunyon requested changes

2022-09-30 20:58 UTC, mattrunyon commented on packages/console/src/monaco/MonacoUtils.ts
> -
I'm guessing you removed this b/c of TS. You can use this instead to keep worker support. Monaco bumped their types at some point after 0.31 I think to extend window

```ts
declare global {
  interface Window {
    MonacoEnvironment: monaco.MonacoEnvironment;
  }
}

window.MonacoEnvironment = {
  getWorker() {
    return editorWorker();
  },
};
```

2022-09-30 23:07 UTC, mattrunyon approved these changes

2022-09-30 23:23 UTC, merged

2023-04-06 18:57 UTC, mofojed commented
Monaco issue is: https://github.com/microsoft/monaco-editor/issues/2947