Slightly reduce padding between console commands
deephaven/web-client-ui pull request #931
Opened 2022-12-06 22:09 UTC by dsmmcken

- Reduces spacing between commands
- Increases button height slightly, but reduces padding
- Aligns gutter "-" with button
- Adopts Button component
- Cleans up CSS a bit, share constants between files
---
- Relates to "Option to increase information density" #885
- Relates to "Reduce the console height to 40/60 split in the default layout" #929

2022-12-06 22:11 UTC, dsmmcken commented
![image](https://user-images.githubusercontent.com/1576283/206034326-def3cd5a-33d1-42d4-8d59-fed9c4e64918.png)

2022-12-07 14:51 UTC, mofojed requested changes

2022-12-07 15:41 UTC, dsmmcken commented on packages/console/src/Console.scss
> +$line-height: 18px;
@use makes sure imports are once only, but I agree, I think one place where I import from two different files in particular was weird and would be better off having a separate partial to contain these variables.

2022-12-08 14:26 UTC, mofojed approved these changes

2022-12-08 14:37 UTC, merged